### ISSUE TITLE
Overall review & styling

### ISSUE THREAD

**Issue by laurentzziu** [laurentzziu/unfuddle-beautifier-chrome#2]
#### General
- [ ] Style website header (flat design, keep theme color)
- [ ] Fix `font-size` issues
- [ ] Style header search bar
- [ ] Replace AJAX loader with a new one (static + animated)
- [ ] Style menu & `add` buttons
- [ ] Style menu dropdowns
- [ ] _*Replace `font-awesome` with `Ionicons`_

#### Milestone Page
- [ ] Finish styling ticket cards (general + for all ticket states + hover)
- [ ] Fix commets icon positioning issue
- [ ] Position due-date icon
- [ ] Position & style Quick Add input

#### Single Issue Page
- [ ] Style header + title
- [ ] Style status selection
- [ ] Fix `font-size` issue
- [ ] Style comments section
- [ ] Style text editor
- [ ] Always show permalink
- [ ] Replace icon

#### New Ticket form
- [ ] Background color
- [ ] Match overall design
